name: Version Bump (prepare for deploy)

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  NODE_VERSION: 20.8

jobs:
  bump-version:
    name: 'Automated Version Bump'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DESPESAS_PAT }}
      # To bump major -> "BREAKING CHANGE" | "major" | pattern "refactor!: drop node v16"
      # To bump minor -> "feat: new API" | "feature: new API"
      # otherwise it will bump patch
      - uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'CI: bumps version to {{version}}'
